### ISSUE TITLE
At Risk Age

### ISSUE THREAD

**Issue by adeniro21** [dsi-principles-prog/midterm-adeniro21#2]
In 2015, adults aged 45 to 64 were the most diagnosed age group for diabetes. I want to have a feature that identifies people over the age of 44.

The idea for creating this new feature is similar to the logic behind having the "is_obese" variable. The data set is not extremely granular since it only contains numeric variables related to health measurements. We can gain more detail by creating groupings based upon threshold values within variables. Adding this context could allow us to see and compare trends better based upon being able to group similar observations together.

The function should take a dataframe and a vector containing what it is you want to mutate. In this case it will be "age" since this is what contains the age data for our observations. The function should mutate the data frame to create a new logical (true or false) vector that will be "true" if someone is over the age of 44 and "false" if otherwise.

It should then output the dataframe ordering the new feature at the front, followed by "age" and then everything else.

The expected outcome should look something like this as the first two columns in the output dataframe once the function is called:

<img width="71" alt="mutate_age_outcome" src="https://user-images.githubusercontent.com/36495522/67644662-5b0e9580-f8f1-11e9-93f1-a70ae670631e.PNG">

Feel free to include the function call in the "ModelDF" named code chunk right before the select statement in order to complete the augmented dataframe. Then run a simple assert statement in the "AssertFunctions" code chunk on the new feature to ensure its values only contain "true" or "false."

**Comment by junxianxiao** [comment]
The request is clear! I have already create a chunk whose outcome is the same as your example.
